name: Deploy to Sweb
on:
  push:
    branches: [ main ] # Убедись, что твоя ветка называется main, а не master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install and Build
        run: |
          bun install
          bun run build

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }} # Используем ключ вместо пароля
          port: 22
          source: "dist/*" # Папка, куда Bun/Vite собирает проект
          target: "/home/d/dreshka324/agroautomation.online/public_html/" # Полный путь на Sweb
          strip_components: 1
