name: Deploy to Sweb
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install and Build
        run: |
          bun install
          bun run build

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "dist/*" # В Bun/Vite папка сборки часто называется dist, а не build. Проверь это!
          target: "public_html/"
          strip_components: 1
